/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Office(props) {
  const { nodes, materials } = useGLTF('/materials/room.glb')
  return (
    <group {...props} dispose={null}>
      {/* // lamp light */}
      {/* <pointLight position={[-6, 4, -4]} intensity={10} /> */}

      <mesh
        name="Mirror"
        castShadow
        receiveShadow
        geometry={nodes.Mirror.geometry}
        material={materials.Mat}
        position={[0.635, 0.117, 5.87]}
        rotation={[Math.PI, -1.123, Math.PI]}
      />
      <mesh
        name="photo-frame-to-modify"
        castShadow
        receiveShadow
        geometry={nodes['photo-frame-to-modify'].geometry}
        material={nodes['photo-frame-to-modify'].material}
        position={[2.529, 7.418, -0.488]}
        rotation={[0.151, 0, 0]}
      />
      <mesh
        name="mirror-element-to-modify"
        castShadow
        receiveShadow
        geometry={nodes['mirror-element-to-modify'].geometry}
        material={nodes['mirror-element-to-modify'].material}
        position={[0.635, 0.117, 5.87]}
        rotation={[Math.PI, -1.123, Math.PI]}
      />
      <group
        name="pCube102001"
        position={[3.134, 4.983, 0.546]}
        rotation={[1.571, 0.007, 1.543]}
        scale={[0.073, 0.05, 0.041]}>
        <mesh
          name="pCube102_1001"
          castShadow
          receiveShadow
          geometry={nodes.pCube102_1001.geometry}
          material={materials.blinn3SG}
        />
        <mesh
          name="pCube102_1001_1"
          castShadow
          receiveShadow
          geometry={nodes.pCube102_1001_1.geometry}
          material={materials.Atlas}
        />
      </group>
      <group
        name="Node"
        position={[-1.972, 0.997, -5.508]}
        rotation={[Math.PI, -0.008, Math.PI]}
        scale={[3.299, 4.959, 4.959]}>
        <mesh
          name="Node-Mesh005"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh005'].geometry}
          material={materials['mat23.006']}
        />
        <mesh
          name="Node-Mesh005_1"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh005_1'].geometry}
          material={materials.mat17}
        />
        <mesh
          name="Node-Mesh005_2"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh005_2'].geometry}
          material={materials['mat16.002']}
        />
        <mesh
          name="Node-Mesh005_3"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh005_3'].geometry}
          material={materials.mat20}
        />
      </group>
      <group name="RootNode004" position={[1.56, 1.456, -5.85]}>
        <group name="FlowerPot8" position={[0, 1.37, 0]} scale={[1.947, 2.851, 1.947]}>
          <mesh
            name="FlowerPot8_1"
            castShadow
            receiveShadow
            geometry={nodes.FlowerPot8_1.geometry}
            material={materials.LeafFlowerPot8}
          />
          <mesh
            name="FlowerPot8_2"
            castShadow
            receiveShadow
            geometry={nodes.FlowerPot8_2.geometry}
            material={materials.VaseFlowerPot8}
          />
          <mesh
            name="FlowerPot8_3"
            castShadow
            receiveShadow
            geometry={nodes.FlowerPot8_3.geometry}
            material={materials.GroundFlowerPot8}
          />
        </group>
      </group>
      <group name="Node001" position={[-5.099, 3.625, -6.211]}>
        <mesh
          name="Node-Mesh006"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh006'].geometry}
          material={materials['mat20.001']}
        />
        <mesh
          name="Node-Mesh006_1"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh006_1'].geometry}
          material={materials['mat21.001']}
        />
        <mesh
          name="Node-Mesh006_2"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh006_2'].geometry}
          material={materials['mat25.001']}
        />
        <mesh
          name="Node-Mesh006_3"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh006_3'].geometry}
          material={materials.mat22}
        />
        <mesh
          name="Node-Mesh006_4"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh006_4'].geometry}
          material={materials.mat19}
        />
        <mesh
          name="Node-Mesh006_5"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh006_5'].geometry}
          material={materials['mat23.007']}
        />
      </group>
      <group
        name="RootNode005"
        position={[0.539, 0.152, 7.504]}
        rotation={[0, 0.289, 0]}
        scale={2.983}>
        <mesh
          name="Dumbbell"
          castShadow
          receiveShadow
          geometry={nodes.Dumbbell.geometry}
          material={materials['Material.004']}
          position={[0.001, 0.08, 0]}
          rotation={[0, 0.289, 0]}
          scale={100}
        />
        <mesh
          name="Dumbbell001"
          castShadow
          receiveShadow
          geometry={nodes.Dumbbell001.geometry}
          material={materials['Material.004']}
          position={[-0.015, 0.123, -0.086]}
          rotation={[2.147, 1.187, -2.717]}
          scale={100}
        />
      </group>
      <group
        name="Node002"
        position={[1.969, 0.211, 7.685]}
        rotation={[0.057, -1.516, 0.014]}
        scale={[0.424, 0.603, 0.603]}>
        <mesh
          name="Node-Mesh007"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh007'].geometry}
          material={materials['lambert4SG.001']}
        />
        <mesh
          name="Node-Mesh007_1"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh007_1'].geometry}
          material={materials['lambert3SG.001']}
        />
        <mesh
          name="Node-Mesh007_2"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh007_2'].geometry}
          material={materials['lambert2SG.001']}
        />
      </group>
      <group name="Node005" position={[-5.85, 3.843, -7.255]} rotation={[Math.PI, -1.54, Math.PI]}>
        <mesh
          name="Node-Mesh008"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh008'].geometry}
          material={materials['mat21.002']}
        />
        <mesh
          name="Node-Mesh008_1"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh008_1'].geometry}
          material={materials['mat15.003']}
        />
      </group>
      <group name="RootNode006" position={[-5.194, 1.022, -6.123]} scale={0.232}>
        <mesh
          name="Circle"
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials['Material.005']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          name="eliminate-lavaLight-to-modify"
          castShadow
          receiveShadow
          geometry={nodes['eliminate-lavaLight-to-modify'].geometry}
          material={materials['Material.006']}
          position={[0, 3.042, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          name="Icosphere"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere.geometry}
          material={materials['Material.007']}
          position={[-0.219, 1.824, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={46.17}
        />
        <mesh
          name="Icosphere001"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere001.geometry}
          material={materials['Material.007']}
          position={[0.202, 2.513, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={25.185}
        />
        <mesh
          name="Icosphere002"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere002.geometry}
          material={materials['Material.007']}
          position={[-0.246, 2.852, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={19.422}
        />
        <mesh
          name="Icosphere003"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere003.geometry}
          material={materials['Material.007']}
          position={[0.131, 3.235, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={19.422}
        />
        <mesh
          name="Icosphere004"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004.geometry}
          material={materials['Material.007']}
          position={[-0.027, 3.711, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={16.962}
        />
        <mesh
          name="Icosphere005"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere005.geometry}
          material={materials['Material.007']}
          position={[0.027, 4.165, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={13.53}
        />
      </group>
      <group
        name="Cube"
        position={[0.552, 6.007, -6.361]}
        rotation={[0, -1.563, 0]}
        scale={[1.631, 1, 1]}>
        <mesh
          name="Cube-Mesh"
          castShadow
          receiveShadow
          geometry={nodes['Cube-Mesh'].geometry}
          material={materials.Top}
        />
        <mesh
          name="Cube-Mesh_1"
          castShadow
          receiveShadow
          geometry={nodes['Cube-Mesh_1'].geometry}
          material={materials.Supports}
        />
      </group>
      <group
        name="Lamborghini_Aventador_Body"
        position={[0.058, 6.305, -6.412]}
        rotation={[0, -0.463, 0]}
        scale={0.002}>
        <mesh
          name="Lamborghini_Aventador_Body_1"
          castShadow
          receiveShadow
          geometry={nodes.Lamborghini_Aventador_Body_1.geometry}
          material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG}
        />
        <mesh
          name="Lamborghini_Aventador_Body_1_1"
          castShadow
          receiveShadow
          geometry={nodes.Lamborghini_Aventador_Body_1_1.geometry}
          material={materials._Lamborghini_AventadorLamborghini_Aventador_GlassSG}
        />
      </group>
      <group name="RootNode007" position={[0.955, 6.492, -6.411]} scale={0.374}>
        <mesh
          name="Rock3"
          castShadow
          receiveShadow
          geometry={nodes.Rock3.geometry}
          material={materials.Rock3}
          position={[0, 0.332, 0]}
          rotation={[0, 0.738, -1.292]}
          scale={0.776}
        />
      </group>
      <group name="RootNode008" position={[-3.059, 4.214, -7.203]} scale={5.321}>
        <mesh
          name="Wall_corkboard_with_post_it_notes"
          castShadow
          receiveShadow
          geometry={nodes.Wall_corkboard_with_post_it_notes.geometry}
          material={materials['Material.008']}
          position={[0, 0.064, 0]}
          scale={100}
        />
      </group>
      <group name="group1534886875001" position={[1.508, 1.469, -3.164]}>
        <mesh
          name="mesh1534886875001"
          castShadow
          receiveShadow
          geometry={nodes.mesh1534886875001.geometry}
          material={materials.legs_of_desk}
        />
        <mesh
          name="mesh1534886875001_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh1534886875001_1.geometry}
          material={materials.mat23}
        />
      </group>
      <mesh
        name="Cube002"
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['07___Default']}
        position={[1.358, 2.838, -1.785]}
        rotation={[-1.087, -0.738, -0.907]}
      />
      <group
        name="group256948792"
        position={[1.424, 3.167, -1.596]}
        rotation={[0.274, -1.125, 0.269]}>
        <mesh
          name="mesh256948792"
          castShadow
          receiveShadow
          geometry={nodes.mesh256948792.geometry}
          material={materials.mat16}
        />
        <mesh
          name="mesh256948792_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh256948792_1.geometry}
          material={materials['mat23.002']}
        />
        <mesh
          name="mesh256948792_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh256948792_2.geometry}
          material={materials['mat17.001']}
        />
        <mesh
          name="mesh256948792_3"
          castShadow
          receiveShadow
          geometry={nodes.mesh256948792_3.geometry}
          material={materials.mat25}
        />
        <mesh
          name="mesh256948792_4"
          castShadow
          receiveShadow
          geometry={nodes.mesh256948792_4.geometry}
          material={materials.mat15}
        />
      </group>
      <mesh
        name="laptop-screen-to-modify"
        castShadow
        receiveShadow
        geometry={nodes['laptop-screen-to-modify'].geometry}
        material={materials['mat17.001']}
        position={[1.424, 3.151, -1.596]}
        rotation={[0.274, -1.125, 0.269]}
      />
      <mesh
        name="group2084455599"
        castShadow
        receiveShadow
        geometry={nodes.group2084455599.geometry}
        material={materials['mat23.001']}
        position={[2.104, 3.609, 0.418]}
        rotation={[0, 1.547, 0]}
      />
      <mesh
        name="Cube012"
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials['07___Default']}
        position={[1.977, 2.671, -0.259]}
        rotation={[0, -0.001, 0]}
      />
      <group
        name="monitor-screen-to-modify"
        position={[2.091, 3.609, 0.418]}
        rotation={[0, 1.547, 0]}>
        <mesh
          name="mesh2084455599001"
          castShadow
          receiveShadow
          geometry={nodes.mesh2084455599001.geometry}
          material={nodes.mesh2084455599001.material}
        />
        <mesh
          name="mesh2084455599001_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh2084455599001_1.geometry}
          material={materials['mat22.001']}
        />
      </group>
      <group
        name="RootNode002"
        position={[1.393, 1.29, -1.223]}
        rotation={[-Math.PI, 0.861, -Math.PI]}>
        <mesh
          name="ExecutiveChair1"
          castShadow
          receiveShadow
          geometry={nodes.ExecutiveChair1.geometry}
          material={materials['LeatherExecutiveChair1.011']}
          position={[0.357, -0.305, -2.799]}
          rotation={[-Math.PI / 2, 0, -0.701]}
        />
      </group>
      <group name="rugRound_1" position={[2.547, 0.136, -0.969]}>
        <mesh
          name="rugRound_3"
          castShadow
          receiveShadow
          geometry={nodes.rugRound_3.geometry}
          material={materials.carpetDarker}
        />
        <mesh
          name="rugRound_3_1"
          castShadow
          receiveShadow
          geometry={nodes.rugRound_3_1.geometry}
          material={materials.carpet}
        />
      </group>
      <group name="RootNode001" position={[0.229, 2.742, 1.225]} rotation={[0, -1.506, 0]}>
        <mesh
          name="Mouse"
          castShadow
          receiveShadow
          geometry={nodes.Mouse.geometry}
          material={materials.Material}
          position={[0.018, -0.186, -0.278]}
        />
      </group>
      <group
        name="group801095923"
        position={[0.527, 2.582, 0.371]}
        rotation={[Math.PI, -1.563, Math.PI]}>
        <mesh
          name="mesh801095923"
          castShadow
          receiveShadow
          geometry={nodes.mesh801095923.geometry}
          material={materials.mat21}
        />
        <mesh
          name="mesh801095923_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh801095923_1.geometry}
          material={materials['mat22.002']}
        />
        <mesh
          name="mesh801095923_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh801095923_2.geometry}
          material={materials['mat16.001']}
        />
      </group>
      <mesh
        name="group877249531"
        castShadow
        receiveShadow
        geometry={nodes.group877249531.geometry}
        material={materials.mat9}
        position={[0.302, 2.768, 0.371]}
        rotation={[Math.PI, -1.563, Math.PI]}
      />
      <group name="RootNode" position={[-0.525, 2.829, -0.228]}>
        <mesh
          name="Mousepad"
          castShadow
          receiveShadow
          geometry={nodes.Mousepad.geometry}
          material={materials.Mousepad}
          position={[1.193, -0.302, 0.59]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        name="Cube014"
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials['mat23.001']}
        position={[2.828, 4.5, 5.011]}
      />
      <mesh
        name="window2-glass-to-modify"
        castShadow
        receiveShadow
        geometry={nodes['window2-glass-to-modify'].geometry}
        material={materials.white}
        position={[2.623, 4.494, 5.01]}
        rotation={[0, 0, 1.569]}
      />
      <mesh
        name="window-glass-to-modify"
        castShadow
        receiveShadow
        geometry={nodes['window-glass-to-modify'].geometry}
        material={materials['white.001']}
        position={[2.363, 4.494, -3.974]}
        rotation={[0, 0, 1.569]}
      />
      <mesh
        name="Cube018"
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials['mat23.003']}
        position={[2.394, 4.072, -3.165]}
      />
      <group name="Cube019" position={[2.557, 4.5, -3.973]}>
        <mesh
          name="Cube023"
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={materials['mat23.003']}
        />
        <mesh
          name="Cube023_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube023_1.geometry}
          material={materials['mat23.001']}
        />
      </group>
      <group name="Cube3844" position={[2.542, 5.862, 1.655]}>
        <mesh
          name="Cube5015"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015.geometry}
          material={materials['Material.001']}
        />
        <mesh
          name="Cube5015_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_1.geometry}
          material={materials['mat23.004']}
        />
        <mesh
          name="Cube5015_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_2.geometry}
          material={materials['mat23.005']}
        />
        <mesh
          name="Cube5015_3"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_3.geometry}
          material={materials['mat8.001']}
        />
        <mesh
          name="Cube5015_4"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_4.geometry}
          material={materials['02___Default']}
        />
        <mesh
          name="Cube5015_5"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_5.geometry}
          material={materials['07___Default']}
        />
        <mesh
          name="Cube5015_6"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_6.geometry}
          material={materials['03___Default']}
        />
        <mesh
          name="Cube5015_7"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_7.geometry}
          material={materials['01___Default']}
        />
        <mesh
          name="Cube5015_8"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_8.geometry}
          material={materials['1A1A1A']}
        />
        <mesh
          name="Cube5015_9"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_9.geometry}
          material={materials['455A64']}
        />
        <mesh
          name="Cube5015_10"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_10.geometry}
          material={materials['039BE5']}
        />
        <mesh
          name="Cube5015_11"
          castShadow
          receiveShadow
          geometry={nodes.Cube5015_11.geometry}
          material={materials.belt}
        />
      </group>
      <mesh
        name="GP_Layer002"
        castShadow
        receiveShadow
        geometry={nodes.GP_Layer002.geometry}
        material={materials['mat23.001']}
        position={[2.192, 3.726, -0.726]}
        rotation={[0, 1.262, 1.587]}
      />
      <mesh
        name="GP_Layer"
        castShadow
        receiveShadow
        geometry={nodes.GP_Layer.geometry}
        material={materials['mat23.001']}
        position={[3.2, 4.997, 1.747]}
        rotation={[0, 0, 1.587]}
      />
      <group name="Node003" position={[2.2, 2.698, 2.275]} rotation={[0, -1.564, 0]}>
        <mesh
          name="Node-Mesh003"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh003'].geometry}
          material={materials.lambert4SG}
        />
        <mesh
          name="Node-Mesh003_1"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh003_1'].geometry}
          material={materials.lambert2SG}
        />
        <mesh
          name="Node-Mesh003_2"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh003_2'].geometry}
          material={materials.lambert9SG}
        />
      </group>
      <group name="Node004" position={[2.204, 2.816, -0.286]} rotation={[0, -1.564, 0]}>
        <mesh
          name="Node-Mesh004"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh004'].geometry}
          material={materials.lambert4SG}
        />
        <mesh
          name="Node-Mesh004_1"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh004_1'].geometry}
          material={materials.lambert2SG}
        />
        <mesh
          name="Node-Mesh004_2"
          castShadow
          receiveShadow
          geometry={nodes['Node-Mesh004_2'].geometry}
          material={materials.lambert9SG}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/materials/room.glb')
